### PR TITLE
Add Travis CI testing

### PR DESCRIPTION
**Pull request by fredrikaverpil**
This PR makes [Travis CI](https://travis-ci.com) execute all the nose tests on Ubuntu 14.04 (Trusty).

## Steps required to enable testing in `eoyilmaz/stalker`

@eoyilmaz Log into Travis CI using your Github credentials ([here](https://travis-ci.com)) and enable Travis CI testing for the `stalker` repository. You can optionally disable testing if the `.travis.yml` file is unavailable in the settings. This is good for branches without this file.

You can add a badge to the top of the README to show the status of the tests when you've activated Travis CI for `eoyilmaz/stalker`

[Build Status](https://travis-ci.org/fredrikaverpil/stalker)

Just replace my git URL with yours):

    [Build Status](https://travis-ci.org/fredrikaverpil/stalker)

## Nosetests log/output

You can see the last tests (nosetests log), which were run from my fork, here: https://travis-ci.org/fredrikaverpil/stalker/builds/200680548

I'm using the same command as you have in `doTests`:

    nosetests $@ --verbosity=1 --cover-erase --with-coverage --cover-package=stalker

The Stalker code is untouched.

## Failing tests

For some reason, some of the tests are failing with the following two errors. I'm also getting these when running the tests on my macOS laptop. Not sure why just now. Do you have any idea why they may be failing?

#### Error 1
```python
Traceback (most recent call last):
  File "/home/travis/build/fredrikaverpil/stalker/tests/models/test_studio.py", line 892, in test_schedule_will_schedule_the_tasks_with_the_given_scheduler
    self.test_studio.schedule()
  File "/home/travis/build/fredrikaverpil/stalker/stalker/models/studio.py", line 423, in schedule
    result = self.scheduler.schedule()
  File "/home/travis/build/fredrikaverpil/stalker/stalker/models/schedulers.py", line 722, in schedule
    stderr=subprocess.PIPE
  File "/opt/python/2.7.12/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/opt/python/2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

#### Error 2
```python
Traceback (most recent call last):
  File "/home/travis/build/fredrikaverpil/stalker/tests/models/test_task.py", line 202, in tearDown
    DBSession.commit()
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 459, in commit
    self._assert_active(prepared_ok=True)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) update or delete on table "SimpleEntities" violates foreign key constraint "Ticket_SimpleEntities_simple_entity_id_fkey" on table "Ticket_SimpleEntities"
DETAIL:  Key (id)=(182) is still referenced from table "Ticket_SimpleEntities".
 [SQL: 'DELETE FROM "SimpleEntities" WHERE "SimpleEntities".id = %(id)s'] [parameters: {'id': 182}]
```

It's possible that **Error 2** is caused by **Error 1**.

### CODE REVIEW

**Comment by fredrikaverpil** [comment]
I'm trying this solution to the rollback issue: http://stackoverflow.com/questions/8870217/sqlalchemy-nested-rollback-error

**Comment by fredrikaverpil** [comment]
I don't know... reverting that too. We're back to just having added `.travis.yml` without any code change.

@eoyilmaz do you really run all these tests without these errors?

**Comment by eoyilmaz** [comment]
Hi Fredrik,

Thanks for informing me about Travic CI it seems nice (but expensive for me to afford).

Error 1, as far as I understand is related with missing TaskJuggler executable (tj3) on your system. The second one seems to be related with a "query invoked auto flush" and it is probably my fault, I've recently fixed a couple of these problems on one of my local branches.

And yes, I really run all of these tests without any major problems. I mean there are a couple of warnings which is related with the task juggler representations of the data, where you get different IDs for the same data when you run the whole tests or just an individual test and they are ok to ignore.

In the next couple of days or so I will merge my current development branch, in which all the ``datetime`` values will now be TimeZone aware. And the system will only work with PostgreSQL and there will be a couple of other new minor features.

Thanks for the PR.

Cheers,

**Comment by fredrikaverpil** [comment]
> Thanks for informing me about Travic CI it seems nice (but expensive for me to afford).

No no, it's 100% free for open source projects. Unless you meant time you need to spend maintaining the `.travis.yml` file 😄

**Comment by fredrikaverpil** [comment]
> TaskJuggler

Hm, did I forget to install that perhaps?
I'll have a look.

**Comment by fredrikaverpil** [comment]
I realize I've never installed TaskJuggler and still we've been running Stalker for a long time now without any issues.

Which version of TaskJuggler are you using?

**Pull request merged**
